version: 2

defaults: &defaults
  working_directory: ~/ledger-live-desktop
  environment:
    BASH_ENV: "~/.bashrc"

jobs:
  build:
    <<: *defaults
    macos:
      xcode: "9.4.1"
    steps:
      - checkout
      - run: bash scripts/ci/macos-setup.sh
      - run: cat ~/.bashrc
      - run: node --version
      - restore_cache:
          keys:
            - v8-yarn-packages-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: v8-yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
#      - run: sudo security add-trusted-cert -d -r trustRoot -k /Library/Keychains/System.keychain <certificate>
      - run: yarn release
